Feature: Subsite compatibility #3
signify-nz/silverstripe-solr-search pull request #6
Opened 2024-12-10 04:01 UTC by sig-peggy

Meeting requirements identified in #3 plus additional functions:

- Behaviour for indexed classes which do not have a SubsiteID field - these appear on all subsites
- Behaviour when Files are indexed which generally do not have their own SubsiteID set but can inherit view permissions based on the parent Folder SubsiteID:
  - Optional File extension to get the SubsiteID from the parent Folder so that Files that can't be viewed on a subsite will not appear in the results count
  - Show main site Files across all subsites (to align with other Subsite module behaviour) unless a config option is changed to prevent this

2024-12-11 04:04 UTC, sig-sam requested changes
There are a couple of minor documentation issues. Otherwise, it looks pretty good. I can see that all the expected behaviour has been implemented.

If you haven't already considered this, for QA testing, it might be good to deploy to two sites: one with subsites and the other without.

2024-12-11 04:04 UTC, sig-sam commented on src/Extensions/FileSubsiteSearchExtension.php
> +class FileSubsiteSearchExtension extends Extension
minor: Missing a docblock.

2024-12-11 04:04 UTC, sig-sam commented on src/Extensions/SubsitesDocumentFactoryExtension.php
> +class SubsitesDocumentFactoryExtension extends Extension
minor: Add `@package` and `@property` annotations for consistency.

2024-12-11 04:25 UTC, sig-peggy commented
Fixed noted doc blocks.
I have got a plan for testing with and without subsites generally, but the one lined up with subsites doesn't cover any other kinds of classes besides SiteTree so I have been pondering the best way to cover those parts in QA.

2024-12-11 20:43 UTC, sig-sam approved these changes

2024-12-11 22:10 UTC, sig-steve commented on src/Extensions/FileSubsiteSearchExtension.php
> + * @copyright Copyright (c) 2024 - now() Signify Ltd
I suggest **not** using the cutesy `2024 - now()`. Lawyers are not known for their appreciation of cuteness.

I think this is sufficient:

```
@copyright Copyright 2024 Signify Ltd
```

2024-12-11 22:14 UTC, sig-steve commented
There are other occurrences of the "Copyright (c) 2024 - now() Signify Ltd" that I'd like to see changed. I only noted the first.

2024-12-11 22:25 UTC, sig-peggy commented
Updated the 2 Signify copyright lines - the other copyright lines added in this work are Firesphere ones in files that were copied from their subsites module as a starting point and then changed to meet our needs. @sig-steve I assume we still want to leave their copyright messages alone even if they are more 'cutesy' than we'd prefer?

2024-12-11 22:30 UTC, sig-steve commented
Yes. We mustn't touch their copyright statements. Thanks!

2024-12-17 21:02 UTC, sig-peggy commented
Testing completed on subsites with combined search results, subsites with separate search results, and a site without subsites. All tests passed.

2024-12-17 21:02 UTC, merged